#!/bin/bash

DB_NAME=TEST_DB
DIR_NAME=test_db

ARTLOG_PATH=/db2/db2log/actlog_$DIR_NAME
ARCLOG_PATH=/db2/db2log/arclog_$DIR_NAME
DBDATA_PATH=/db2/db2data/$DIR_NAME
DBTEMP_PATH=/db2/db2data/$DIR_NAME/tempspace
DBBACK_PATH=/db2/db2data/db2backup

echo "ARTLOG_PATH=$ARTLOG_PATH"
echo "ARCLOG_PATH=$ARCLOG_PATH"
echo "DBDATA_PATH=$DBDATA_PATH"
echo "DBTEMP_PATH=$DBTEMP_PATH"
echo "DBBACK_PATH=$DBBACK_PATH"

mkdir -p $ARTLOG_PATH
mkdir -p $ARCLOG_PATH
mkdir -p $DBDATA_PATH
mkdir -p $DBTEMP_PATH
mkdir -p $DBBACK_PATH

echo "[db2 stop]"
db2stop force

echo "[db2set ...1]"

echo "[db2 update  ...1]"
#
echo "[db2start]"
db2start

echo "[db2 create db : /$DBDATA_PATH]"
db2 CREATE DATABASE $DB_NAME AUTOMATIC STORAGE YES  ON "/$DBDATA_PATH" USING CODESET UTF-8 TERRITORY CN COLLATE USING SYSTEM PAGESIZE 8192

echo "[db2 update ...2]"
db2 update db cfg for $DB_NAME using NEWLOGPATH $ARTLOG_PATH
db2 update db cfg for $DB_NAME using LOGFILSIZ 38400
db2 update db cfg for $DB_NAME using LOGPRIMARY 60
db2 update db cfg for $DB_NAME using LOGSECOND 40
db2 update db cfg for $DB_NAME using CATALOGCACHE_SZ 2048
db2 update db cfg for $DB_NAME using STMTHEAP AUTOMATIC
db2 update db cfg for $DB_NAME using LOGBUFSZ 4096
db2 update db cfg for $DB_NAME using CHNGPGS_THRESH 60
db2 update db cfg for $DB_NAME using LOCKTIMEOUT 60
#db2 update db cfg for $DB_NAME using LOGRETAIN ON

echo "[db2 backup]"

#db2 update db cfg for BVS using LOGARCHMETH1 "disk:$ARCLOG_PATH"
db2 backup db $DB_NAME to $DBBACK_PATH
#
echo "[db2 connect to BVS]"
db2 CONNECT TO $DB_NAME
#db2 GRANT  CREATETAB,BINDADD,CONNECT,CREATE_NOT_FENCED_ROUTINE,LOAD,CREATE_EXTERNAL_ROUTINE,QUIESCE_CONNECT ON DATABASE  TO USER $DB_USER
#
echo "[db2 create schema bvs]"
#db2 create schema BVS
#db2 GRANT  CREATEIN,DROPIN,ALTERIN ON SCHEMA BVS TO USER $DB_USER

  
#TABLE BUFFERPOOL 
echo "[db2 create bufferpool]"

db2 CREATE BUFFERPOOL DMSBP01 IMMEDIATE   SIZE  32000 PAGESIZE 32K
#db2 CREATE BUFFERPOOL DMSBP02 IMMEDIATE  SIZE  32000  PAGESIZE 32K 
#db2 CREATE BUFFERPOOL DMSBP03 IMMEDIATE  SIZE  32000  PAGESIZE 32K 

 #TABLE SPACES
 echo "[db2 create tablespace]"
db2 CREATE LARGE TABLESPACE ACS_TBS01 IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"  PAGESIZE 32K  MANAGED BY AUTOMATIC STORAGE   EXTENTSIZE 128  PREFETCHSIZE AUTOMATIC  BUFFERPOOL "DMSBP01"  DROPPED TABLE RECOVERY ON
#db2 CREATE LARGE TABLESPACE  DMSSPTB02  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"  PAGESIZE 32K  MANAGED BY AUTOMATIC STORAGE   EXTENTSIZE 128  PREFETCHSIZE AUTOMATIC  BUFFERPOOL "DMSBP01" DROPPED TABLE RECOVERY ON
#db2 CREATE LARGE TABLESPACE  DMSSPTB03  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"  PAGESIZE 32K  MANAGED BY AUTOMATIC STORAGE   EXTENTSIZE 128  PREFETCHSIZE AUTOMATIC  BUFFERPOOL "DMSBP01" DROPPED TABLE RECOVERY ON    
#db2 CREATE LARGE TABLESPACE DMSSPIDX01 IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"  PAGESIZE 32K  MANAGED BY AUTOMATIC STORAGE   EXTENTSIZE 128  PREFETCHSIZE AUTOMATIC  BUFFERPOOL "DMSBP01" DROPPED TABLE RECOVERY ON
#db2 CREATE  TEMPORARY TABLESPACE DMSTEMPSP01 IN DATABASE PARTITION GROUP "IBMTEMPGROUP"  PAGESIZE 32K  MANAGED BY AUTOMATIC STORAGE  EXTENTSIZE 128  PREFETCHSIZE AUTOMATIC  BUFFERPOOL "DMSBP03" NO FILE SYSTEM CACHING DROPPED TABLE RECOVERY OFF
#db2 CREATE USER TEMPORARY TABLESPACE DMSTEMPSP01 IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"  PAGESIZE 32K  MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 128  PREFETCHSIZE AUTOMATIC  BUFFERPOOL "DMSBP01" NO FILE SYSTEM CACHING DROPPED TABLE RECOVERY OFF
#USING ("$DBTEMP_PATH/tstmp") 
#db2 CREATE SYSTEM TEMPORARY TABLESPACE DMSTEMPSP02 IN DATABASE PARTITION GROUP "IBMTEMPGROUP"  PAGESIZE 32K  MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 128  PREFETCHSIZE AUTOMATIC  BUFFERPOOL "DMSBP01" NO FILE SYSTEM CACHING DROPPED TABLE RECOVERY OFF
# USING ("$DBTEMP_PATH/tsustmp")



#OVERHEAD -1.00
#TRANSFERRATE -1.00
echo "[db2 grant use to user $DB_USER]"
#db2 GRANT USE OF TABLESPACE "DMSSPTB01" TO USER "$DB_USER" WITH GRANT OPTION
#db2 GRANT USE OF TABLESPACE "DMSSPTB02" TO USER "$DB_USER" WITH GRANT OPTION
#db2 GRANT USE OF TABLESPACE "DMSSPTB03" TO USER "$DB_USER" WITH GRANT OPTION
#db2 GRANT USE OF TABLESPACE "DMSSPIDX01" TO USER "$DB_USER" WITH GRANT OPTION
#db2 GRANT USE OF TABLESPACE "DMSTEMPSP01" TO USER "$DB_USER" WITH GRANT OPTION

#db2 GRANT USE OF TABLESPACE DMSTEMPSP01 TO PUBLIC WITH GRANT OPTION 
#db2 GRANT USE OF TABLESPACE DMSTEMPSP02 TO PUBLIC WITH GRANT OPTION 
